import { useLocalization } from '@context/localization';

export const getCategories = () => {
  const { t } = useLocalization();
  return [
    { value: '', label: t('common.category') },
    { value: '2', label: t('category.entertainment') },
    { value: '3', label: t('category.food') },
    { value: '4', label: t('category.gifts') },
    { value: '5', label: t('category.household') },
    { value: '6', label: t('category.housing') },
    { value: '7', label: t('category.health') },
    { value: '9', label: t('category.transport') },
    { value: '10', label: t('category.utilities') },
    { value: '1', label: t('category.clothing') },
    { value: '12', label: t('category.family') },
    { value: '8', label: t('category.personal') },
    { value: '11', label: t('category.travel') },
    { value: '13', label: t('category.investment') },
  ];
};

// Fallback categories for when localization is not available
export const categories = [
  { value: '', label: 'Category' },
  { value: '2', label: 'Entertainment' },
  { value: '3', label: 'Food' },
  { value: '4', label: 'Gifts' },
  { value: '5', label: 'Household Items/Supplies' },
  { value: '6', label: 'Housing' },
  { value: '7', label: 'Medical / Healthcare' },
  { value: '9', label: 'Transportation' },
  { value: '10', label: 'Utilities' },
  { value: '1', label: 'Clothing' },
  { value: '12', label: 'Family' },
  { value: '8', label: 'Personal' },
  { value: '11', label: 'Travel' },
  { value: '13', label: 'Investment' },
];

export const getMonthNames = () => {
  const { t } = useLocalization();
  return [
    t('months.january'),
    t('months.february'),
    t('months.march'),
    t('months.april'),
    t('months.may'),
    t('months.june'),
    t('months.july'),
    t('months.august'),
    t('months.september'),
    t('months.october'),
    t('months.november'),
    t('months.december'),
  ];
};

// Fallback month names for when localization is not available
export const monthNames = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const currencies = {
  AED: 'United Arab Emirates Dirham',
  AFN: 'Afghan Afghani',
  ALL: 'Albanian Lek',
  AMD: 'Armenian Dram',
  ANG: 'Netherlands Antillean Guilder',
  AOA: 'Angolan Kwanza',
  ARS: 'Argentine Peso',
  AUD: 'Australian Dollar',
  AWG: 'Aruban Florin',
  AZN: 'Azerbaijani Manat',
  BAM: 'Bosnia-Herzegovina Convertible Mark',
  BBD: 'Barbadian Dollar',
  BDT: 'Bangladeshi Taka',
  BGN: 'Bulgarian Lev',
  BHD: 'Bahraini Dinar',
  BIF: 'Burundian Franc',
  BMD: 'Bermudan Dollar',
  BND: 'Brunei Dollar',
  BOB: 'Bolivian Boliviano',
  BRL: 'Brazilian Real',
  BSD: 'Bahamian Dollar',
  BTC: 'Bitcoin',
  BTN: 'Bhutanese Ngultrum',
  BWP: 'Botswanan Pula',
  BYN: 'Belarusian Ruble',
  BZD: 'Belize Dollar',
  CAD: 'Canadian Dollar',
  CDF: 'Congolese Franc',
  CHF: 'Swiss Franc',
  CLF: 'Chilean Unit of Account (UF)',
  CLP: 'Chilean Peso',
  CNH: 'Chinese Yuan (Offshore)',
  CNY: 'Chinese Yuan',
  COP: 'Colombian Peso',
  CRC: 'Costa Rican Colón',
  CUC: 'Cuban Convertible Peso',
  CUP: 'Cuban Peso',
  CVE: 'Cape Verdean Escudo',
  CZK: 'Czech Republic Koruna',
  DJF: 'Djiboutian Franc',
  DKK: 'Danish Krone',
  DOP: 'Dominican Peso',
  DZD: 'Algerian Dinar',
  EGP: 'Egyptian Pound',
  ERN: 'Eritrean Nakfa',
  ETB: 'Ethiopian Birr',
  EUR: 'Euro',
  FJD: 'Fijian Dollar',
  FKP: 'Falkland Islands Pound',
  GBP: 'British Pound Sterling',
  GEL: 'Georgian Lari',
  GGP: 'Guernsey Pound',
  GHS: 'Ghanaian Cedi',
  GIP: 'Gibraltar Pound',
  GMD: 'Gambian Dalasi',
  GNF: 'Guinean Franc',
  GTQ: 'Guatemalan Quetzal',
  GYD: 'Guyanaese Dollar',
  HKD: 'Hong Kong Dollar',
  HNL: 'Honduran Lempira',
  HRK: 'Croatian Kuna',
  HTG: 'Haitian Gourde',
  HUF: 'Hungarian Forint',
  IDR: 'Indonesian Rupiah',
  ILS: 'Israeli New Sheqel',
  IMP: 'Manx pound',
  INR: 'Indian Rupee',
  IQD: 'Iraqi Dinar',
  IRR: 'Iranian Rial',
  ISK: 'Icelandic Króna',
  JEP: 'Jersey Pound',
  JMD: 'Jamaican Dollar',
  JOD: 'Jordanian Dinar',
  JPY: 'Japanese Yen',
  KES: 'Kenyan Shilling',
  KGS: 'Kyrgystani Som',
  KHR: 'Cambodian Riel',
  KMF: 'Comorian Franc',
  KPW: 'North Korean Won',
  KRW: 'South Korean Won',
  KWD: 'Kuwaiti Dinar',
  KYD: 'Cayman Islands Dollar',
  KZT: 'Kazakhstani Tenge',
  LAK: 'Laotian Kip',
  LBP: 'Lebanese Pound',
  LKR: 'Sri Lankan Rupee',
  LRD: 'Liberian Dollar',
  LSL: 'Lesotho Loti',
  LYD: 'Libyan Dinar',
  MAD: 'Moroccan Dirham',
  MDL: 'Moldovan Leu',
  MGA: 'Malagasy Ariary',
  MKD: 'Macedonian Denar',
  MMK: 'Myanma Kyat',
  MNT: 'Mongolian Tugrik',
  MOP: 'Macanese Pataca',
  MRU: 'Mauritanian Ouguiya',
  MUR: 'Mauritian Rupee',
  MVR: 'Maldivian Rufiyaa',
  MWK: 'Malawian Kwacha',
  MXN: 'Mexican Peso',
  MYR: 'Malaysian Ringgit',
  MZN: 'Mozambican Metical',
  NAD: 'Namibian Dollar',
  NGN: 'Nigerian Naira',
  NIO: 'Nicaraguan Córdoba',
  NOK: 'Norwegian Krone',
  NPR: 'Nepalese Rupee',
  NZD: 'New Zealand Dollar',
  OMR: 'Omani Rial',
  PAB: 'Panamanian Balboa',
  PEN: 'Peruvian Nuevo Sol',
  PGK: 'Papua New Guinean Kina',
  PHP: 'Philippine Peso',
  PKR: 'Pakistani Rupee',
  PLN: 'Polish Zloty',
  PYG: 'Paraguayan Guarani',
  QAR: 'Qatari Rial',
  RON: 'Romanian Leu',
  RSD: 'Serbian Dinar',
  RUB: 'Russian Ruble',
  RWF: 'Rwandan Franc',
  SAR: 'Saudi Riyal',
  SBD: 'Solomon Islands Dollar',
  SCR: 'Seychellois Rupee',
  SDG: 'Sudanese Pound',
  SEK: 'Swedish Krona',
  SGD: 'Singapore Dollar',
  SHP: 'Saint Helena Pound',
  SLL: 'Sierra Leonean Leone',
  SOS: 'Somali Shilling',
  SRD: 'Surinamese Dollar',
  SSP: 'South Sudanese Pound',
  STD: 'São Tomé and Príncipe Dobra (pre-2018)',
  STN: 'São Tomé and Príncipe Dobra',
  SVC: 'Salvadoran Colón',
  SYP: 'Syrian Pound',
  SZL: 'Swazi Lilangeni',
  THB: 'Thai Baht',
  TJS: 'Tajikistani Somoni',
  TMT: 'Turkmenistani Manat',
  TND: 'Tunisian Dinar',
  TOP: "Tongan Pa'anga",
  TRY: 'Turkish Lira',
  TTD: 'Trinidad and Tobago Dollar',
  TWD: 'New Taiwan Dollar',
  TZS: 'Tanzanian Shilling',
  UAH: 'Ukrainian Hryvnia',
  UGX: 'Ugandan Shilling',
  USD: 'United States Dollar',
  UYU: 'Uruguayan Peso',
  UZS: 'Uzbekistan Som',
  VEF: 'Venezuelan Bolívar Fuerte (Old)',
  VES: 'Venezuelan Bolívar Soberano',
  VND: 'Vietnamese Dong',
  VUV: 'Vanuatu Vatu',
  WST: 'Samoan Tala',
  XAF: 'CFA Franc BEAC',
  XAG: 'Silver Ounce',
  XAU: 'Gold Ounce',
  XCD: 'East Caribbean Dollar',
  XDR: 'Special Drawing Rights',
  XOF: 'CFA Franc BCEAO',
  XPD: 'Palladium Ounce',
  XPF: 'CFP Franc',
  XPT: 'Platinum Ounce',
  YER: 'Yemeni Rial',
  ZAR: 'South African Rand',
  ZMW: 'Zambian Kwacha',
  ZWL: 'Zimbabwean Dollar',
};

export const getSuggestions = () => {
  const { t } = useLocalization();
  return {
    '': [],
    1: [t('suggestions.clothing.haine'), t('suggestions.clothing.incaltaminte'), t('suggestions.clothing.pantaloni'), t('suggestions.clothing.tricouri'), 'Nelea', 'Leo'],
    2: [
      t('suggestions.entertainment.happyHour'),
      t('suggestions.entertainment.benzinarie'),
      t('suggestions.entertainment.ceaiCafea'),
      t('suggestions.entertainment.restaurant'),
      t('suggestions.entertainment.ingetata'),
      t('suggestions.entertainment.parc'),
    ],
    3: [t('suggestions.food.market'), t('suggestions.food.apa'), t('suggestions.food.lunch'), t('suggestions.food.inghetata'), t('suggestions.food.strausGlovo')],
    4: [t('suggestions.gifts.flori'), 'Nelea', t('suggestions.gifts.ziDeNastere')],
    5: [t('suggestions.household.igiena'), t('suggestions.household.scutece'), 'Leo'],
    6: [
      t('suggestions.housing.house'),
      t('suggestions.housing.rataJakala'),
      t('suggestions.housing.rataIpoteca'),
      t('suggestions.housing.rataCredConsum'),
      t('suggestions.housing.apartmentRent'),
    ],
    7: [
      t('suggestions.health.farmacie'),
      t('suggestions.health.stomatolog'),
      t('suggestions.health.pediatru'),
      'Nelea',
      'Leo',
      t('suggestions.health.sport'),
      t('suggestions.health.asigurare'),
    ],
    8: [t('suggestions.personal.haircut'), t('suggestions.personal.nails'), 'Nelea'],
    9: [
      t('suggestions.transport.benzina'),
      t('suggestions.transport.motorina'),
      t('suggestions.transport.carService'),
      t('suggestions.transport.lichidParbriz'),
      t('suggestions.transport.carWash'),
      t('suggestions.transport.taxi'),
      t('suggestions.transport.parcare'),
    ],
    10: [t('suggestions.utilities.gaz'), t('suggestions.utilities.lumina'), 'orange', t('suggestions.utilities.bloc')],
    11: ['Romania'],
    12: ['Nelea', 'Leo', t('suggestions.family.gradinita'), t('suggestions.family.jucarii'), t('suggestions.family.terenJoaca')],
    13: [],
    14: [t('suggestions.alcohol.vin'), t('suggestions.alcohol.bere'), t('suggestions.alcohol.whiskey'), t('suggestions.alcohol.cognac'), t('suggestions.alcohol.gin'), t('suggestions.alcohol.cocktails')],
  };
};

// Fallback suggestions for when localization is not available
export const suggestions = {
  '': [],
  1: ['haine', 'incaltaminte', 'pantaloni', 'tricouri', 'Nelea', 'Leo'],
  2: [
    'happy hour',
    'benzinarie',
    'ceai/cafea',
    'restaurant',
    'ingetata',
    'parc',
  ],
  3: ['market', 'apa', 'lunch', 'inghetata', 'straus/glovo food'],
  4: ['flori', 'Nelea', 'zi de nastere'],
  5: ['igiena/curatinie', 'scutece', 'Leo'],
  6: [
    'house',
    'rata la jakala/ffw',
    'rata la ipoteca',
    'rata la cred de consum',
    'apartment rent',
  ],
  7: [
    'farmacie',
    'stomatolog',
    'pediatru',
    'Nelea',
    'Leo',
    'sport',
    'asigurare',
  ],
  8: ['haircut', 'nails', 'Nelea'],
  9: [
    'benzina',
    'motorina',
    'car service',
    'lichid parbriz',
    'car wash',
    'taxi',
    'parcare',
  ],
  10: ['gaz', 'lumina', 'orange', 'bloc'],
  11: ['Romania'],
  12: ['Nelea', 'Leo', 'gradinita', 'jucarii', 'teren de joaca'],
  13: [],
  14: ['vin', 'bere', 'whiskey', 'cognac', 'gin', 'cocktails'],
};

export const notificationType = {
  SUCCESS: 'success',
  ERROR: 'error',
};

export const themeList = {
  'bondi-blue': 'Bondi blue',
  'maximum-green-yellow': 'Maximum green yellow',
  'indian-red': 'Indian red',
  'carrot-orange': 'Carrot Orange',
  saffron: 'Saffron',
  inchworm: 'Inchworm',
  cadetblue: 'Cadet blue',
  'blue-pink-gradient': 'Blue pink gradient',
  'pearl-aqua': 'Pearl Aqua',
  'navy-blue': 'Navy Blue',
  'cambridge-blue': 'Cambridge blue',
};

export const colorMap = {
  'bondi-blue': {
    accentColor: '#00a8ad',
    textColor: '#ffffff', // White contrasts better on teal
  },
  'maximum-green-yellow': {
    accentColor: '#cdf05d',
    textColor: '#333333', // Dark gray for softer contrast on light green-yellow
  },
  'indian-red': {
    accentColor: '#db5463',
    textColor: '#ffffff', // White for high contrast on deep red
  },
  'carrot-orange': {
    accentColor: '#ef9528',
    textColor: '#333333', // Dark gray is softer and more readable on orange
  },
  saffron: {
    accentColor: '#e9c12f',
    textColor: '#333333', // Dark gray works well for a balanced contrast on saffron yellow
  },
  inchworm: {
    accentColor: '#99de5d',
    textColor: '#333333', // Dark gray improves readability on light green
  },
  cadetblue: {
    accentColor: 'cadetblue',
    textColor: '#ffffff', // White contrasts well on cadet blue
  },
  'blue-pink-gradient': {
    accentColor: '#7c6ab9',
    textColor: '#ffffff', // White provides high contrast on blue
  },
  'pearl-aqua': {
    accentColor: '#7bd0c9',
    textColor: '#333333', // Dark gray is more readable on light aqua
  },
  'navy-blue': {
    accentColor: '#40739e',
    textColor: '#ffffff', // White contrasts best on navy blue
  },
  'cambridge-blue': {
    accentColor: '#a6c5a7',
    textColor: '#333333', // Dark gray for better readability on soft green
  },
};

export const availableCharts = [
  'MonthlyTotals',
  'YearAverageTrend',
  'MonthlyComparisonTrend',
  'AllTimeSpendings',
  'MonthlyAverage',
  'MonthlySavingsTrend',
  'MonthlyAverageTrend',
  'DailyAverage',
  'DailyAverageTrend',
  'LastTwoMonthsAverage',
];
